apiVersion: v1
kind: ServiceAccount
metadata:
  name: error
---
apiVersion: v1
kind: Service
metadata:
  name: error
  labels:
    app: error
    service: error
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: error
